var life=100;
var struggles=20;
var happy=10;
var angry=9;
var sad=20;
var sucess=life-(struggles+sad+angry-happy);
console.log("Successful :" + sucess);
var sucessPercentage=((life-sucess)/life)*100;
console.log("Success Percentage: " + sucessPercentage + "%");
var exactpercentage=Math.round(sucessPercentage);
console.log("Exact Success Percentage: " + exactpercentage + "%");
var a=132;
var b=91;
var c=a/b;
console.log("a/b: " + c);
var d=a%b;
console.log("a%b: " + d);
var e=Math.round(c);
console.log("Rounded a/b: " + e);
var f=a>b;
console.log("Is a greater than b? " + f);
var g=a<b;
console.log("Is a less than b? " + g);
console.log(typeof sucess);
console.log(typeof sucessPercentage);
console.log(typeof exactpercentage);
console.log(typeof c);  
console.log(typeof d);
console.log(typeof e);
console.log(typeof f);
console.log(typeof g); 